### ISSUE TITLE
Could not load file or assembly 'P23.MetaTrader4.Manager.ClrWrapper.dll' or one of its dependencies.

### ISSUE THREAD

**Issue by aslabs** [Uriil/MetaTrader4.Manager.Wrapper#106]
Hi Uriil,

I developed a windows service using the wrapper. All worked fine in Visual Studio, then when the tme arrived to release it as a service and install it in our DEV machine I get this error:

```
2017-02-17 16:06:20,939 ERROR TradinexTradingService.Log4NetLogger – System.IO.FileNotFoundException: Could not load file or assembly 'P23.MetaTrader4.Manager.ClrWrapper.dll' or one of its dependencies. The specified module could not be found.
File name: 'P23.MetaTrader4.Manager.ClrWrapper.dll'
   at TradinexTradingService.QuotesProcessor.go()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

All the files are in the currentDirectory. I had to change the current directory from System32, and it worked in Debug mode in my PC (windows 10), but it doesn't work on Windows Server 2008.

I'm using the constructor:
```
System.IO.Directory.SetCurrentDirectory(Environment.CurrentDirectory);
//[...]
ClrWrapper  mt = new ClrWrapper(config.getConnectionParameters(), Environment.CurrentDirectory + "/mtmanapi.dll");
```

Thanks fro your help

**Comment by Uriil** [comment]
U need to install visual c++ 2015 redistributable package version x86

**Comment by aslabs** [comment]
Wow thanks man!
How I didn't think about it. I spent an entire day on this.
Thanks again.

**Comment by Josh-a-e** [comment]
For anyone who ends up here in the future:

**install chocolatey**
```
powershell -NoProfile -ExecutionPolicy unrestricted -Command "Invoke-Expression ((New-Object Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin
```
**use chocolatey to install visual c++ redist package**
```
choco install -y vcredist2015
```

**Comment by Uriil** [comment]
Actually for latest version you might need redist package 2017
