### ISSUE TITLE
System.ArgumentException, at Convert UserRecord

### ISSUE THREAD

**Issue by liqiangsu** [Uriil/MetaTrader4.Manager.Wrapper#139]
I am getting the following exception after the application ran for about 15 hours. It is a 32bit application.
I use 2 instances of the Wrapper, one for the stander-mode, another for the pumping-ex mode.
```
Unhandled Exception: System.ArgumentException: The pointer passed in as a String must not be in the bottom 64K of the process's address space.
   at System.String..ctor(SByte* value)
   at P23.MetaTrader4.Manager.ClrWrapper.Convert(UserRecord* input)
   at P23.MetaTrader4.Manager.ClrWrapper.UserRecordsRequest(IList`1 logins)
...
   at P23.MetaTrader4.Manager.ClrWrapper.ExtendedPumpingNotify(Int32 code, Int32 type, Void* data, Void* param)
```
Why am i getting this error?

**Comment by Uriil** [comment]
I also had this issue, but for me it is extremely rare, maybe few times per year. I suspect, that UserRecord object, that comes from native dll, somehow corrupted, but because it comes so rarely I can not debug it.
